---
name: Agile User Story
description: Submit an issue, formatted as an Agile User Story.
title: "[Story]: As a [user], I want [something], so that [expected outcome]"
labels: ["state: pending", "type: discussion"]
body:
  - type: markdown
    attributes:
      value: |
        - [How to Write Great Agile User Stories](https://sprint.ly/blog/agile-user-stories/)
        - [User stories with examples — Atlassian](https://www.atlassian.com/agile/project-management/user-stories)
  - type: textarea
    id: who
    attributes:
      label: Who are you doing this for?
      description: _As a [persona]._
      placeholder: persona
    validations:
      required: false
  - type: textarea
    id: what
    attributes:
      label: What are you doing?
      description: _I want [something]._
      placeholder: what
    validations:
      required: false
  - type: textarea
    id: why
    attributes:
      label: Why are you doing this?
      description: _So that [expected outcome]._
      placeholder: expected outcome
    validations:
      required: false
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Enumerate the technical details involved in playing/resolving this story.
      render: Markdown
      value: |
        - TBD
        - TBD
    validations:
      required: false
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Describe the criteria necessary to judge an acceptable outcome.
      render: Markdown
      value: |
        - [ ] TBD
        - [ ] TBD
    validations:
      required: false
  - type: textarea
    id: bdd
    attributes:
      label: Tests for Behavior-Driven Development (BDD)
      description: |
        Describe all scenarios that test/validated your [expected outcome].
        This uses [Gherkin syntax](https://cucumber.io/docs/gherkin/reference/), used for [Cucumber-based testing](https://cucumber.io/docs).
      render: Gherkin
      value: |
        Scenario: Title
          Given [context]
            And [some more context]...
          When  [event]
            And [another event]...
          Then  [outcome]
            And [another outcome]...
          But   [not this outcome]
    validations:
      required: false
