---
name: Agile User Story
description: Submit an issue, formatted as an _Agile User Story_.
title: "[Story]: As a _persona_, I want _something_, so that _expected outcome_."
labels: ["state: pending", "type: discussion"]
body:
  - type: markdown
    attributes:
      value: |
        - [How to Write Great Agile User Stories](https://sprint.ly/blog/agile-user-stories/)
        - [User stories with examples — Atlassian](https://www.atlassian.com/agile/project-management/user-stories)
  - type: textarea
    id: who
    attributes:
      label: Who are you doing this for?
      description: As a _persona_.
      placeholder: persona
      render: Markdown
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What are you doing?
      description: I want _something_.
      placeholder: something
      render: Markdown
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why are you doing this?
      description: So that _expected outcome_.
      placeholder: expected outcome
      render: Markdown
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Enumerate the technical details involved in playing/resolving this story.
      value: |
        - TBD
        - TBD
    validations:
      required: false
  - type: textarea
    id: criteria
    attributes:
      label: Acceptance Criteria
      description: Describe the criteria necessary to judge an acceptable outcome.
      value: |
        - [ ] TBD
        - [ ] TBD
    validations:
      required: true
  - type: textarea
    id: tests
    attributes:
      label: Tests for Behavior-Driven Development (BDD)
      description: |
        Describe all scenarios, using [Gherkin syntax](https://cucumber.io/docs/gherkin/reference/), that validate your [expected outcome].
      value: |
        ```gherkin

        Scenario: Title
          Given _context_
            And _some more context_...
          When  _event_
            And _another event_...
          Then  _outcome_
            And _another outcome_...
          But   _not this outcome_

        ```
    validations:
      required: false
