---
name: Delivery

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pull-requests: write

jobs:
  release:
    uses: ./.github/workflows/semantic-release.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_PAT }}
