---
name: Continuous Delivery

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release:
    uses: ./.github/workflows/semantic-release.yml
    secrets:
      token: ${{ secrets.GH_PAT }}
