---
name: Maintain Repository Labels

on:
  label:
    types: [created, edited, deleted]
  push:
    branches: [main]
    paths:
      - .github/labels.json
      - .github/workflows/labels.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  labels:
    uses: ./.github/workflows/label-sync.yml
    # with:
    #   repository: ${{ github.repository }}
    #   config: ./.github/labels.json
    # secrets:
    #   token: ${{ secrets.GITHUB_TOKEN }}
