---
name: GitHub Label Sync
# https://github.com/seantrane/github-label-presets

on:
  workflow_call:
    inputs:
      config:
        description: Labels configuration file path (./.github/labels.json)
        type: string
        default: ./.github/labels.json
      debug:
        description: Enable dry-run sync for debugging
        type: boolean
        default: false
      repository:
        description: GitHub Repository (github_profile/repo_name)
        type: string
        default: ${{ github.repository }}

permissions:
  contents: read
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  labels:
    name: Label Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i -g github-label-sync
      - run: github-label-sync -l ${{ inputs.config }} ${{ inputs.repository }}
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
