---
name: SonarSource, SonarCloud, SonarQube
# https://github.com/SonarSource/sonarcloud-github-action
# https://github.com/SonarSource/sonarqube-scan-action
# https://github.com/SonarSource/sonarqube-quality-gate-action

on:
  workflow_call:
    inputs:
      cert:
        description: If SonarQube uses self-signed certificate, pass a root certificate (in PEM format)
        type: string
        default: ''
      host:
        description: Specify SonarQube Host URL
        type: string
        default: ''
      gate:
        description: Use SonarQube Quality Gate in Status Checks?
        type: boolean
        default: false
      working-directory:
        description: Directory in which to run Sonar Scanner
        type: string
        default: ./
    secrets:
      token:
        required: true

permissions:
  contents: read
  statuses: write
  pull-requests: write

jobs:
  sonar:
    name: SonarSource
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0

      - name: SonarCloud Scan
        if: ${{ inputs.host == '' }}
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ${{ inputs.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # SonarCloud access token should be generated from https://sonarcloud.io/account/security/
          SONAR_TOKEN: ${{ secrets.token }}

      - name: SonarQube Scan
        if: ${{ inputs.host != '' }}
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: ${{ inputs.working-directory }}
        env:
          # SonarQube access token should be generated from https://sonarcloud.io/account/security/
          SONAR_TOKEN: ${{ secrets.token }}
          SONAR_HOST_URL: ${{ inputs.host }}
          # SONAR_ROOT_CERT: ${{ inputs.cert }}

      # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        if: ${{ inputs.host != '' && inputs.gate == true }}
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.token }}
          SONAR_HOST_URL: ${{ inputs.host }}
          # SONAR_ROOT_CERT: ${{ inputs.cert }}

      # Optionally you can use the output from the Quality Gate in another step.
      # The possible outputs of the `quality-gate-status` variable are `PASSED`, `WARN` or `FAILED`.
      - name: SonarQube Quality Gate Status
        if: ${{ inputs.host != '' && inputs.gate == true }}
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
